config/routes.rb
Rails.application.routes.draw do
 	devise_for :users
	root to: 'portfolios#index'

	resources :portfolios, only: [:index, :show] do
		  collection do
		    get 'portfolios_indexer'
		  end
	end
	
	namespace :admin do
			root 'portfolios#index'
			resources :portfolios
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_and_belongs_to_many :technologies, dependent: :destroy
end

app/models/technology.rb
class Technology < ApplicationRecord
	has_and_belongs_to_many :portfolios
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable

  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "admin"
  before_action :require_admin

  # Methods omitted

  def require_admin
    unless user_signed_in? and current_user.admin?
      redirect_to new_user_session_path
    end
  end
  
end

app/controllers/admin/portfolios_controller.rb
class Admin::PortfoliosController < Admin::BaseController
	before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
	before_filter :set_default_response_format, only: [:show, :portfolios_indexer]
  def index
  	@portfolios  = Portfolio.all
  end

  def show
  end

  def new 
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.create(portfolio_params)
    if @portfolio.save
         technologyParams = params[:portfolio][:technologies]
      if technologyParams
         technologyParams.shift
         technologyParams.each { |id|
          @technology = Technology.find_by_id(id)
          @portfolio.technologies << @technology
        }
      end
        redirect_to  admin_portfolios_path
      else
        render 'new'
    end
  end
  
  def edit
  end

  def update
    if @portfolio.update(portfolio_params)
      portfolioTech = params[:portfolio][:technologies]
      portfolioTech.shift
        if @portfolio.technologies != portfolioTech.map(&:to_i)
          pt = @portfolio.technologies #pt = portfolio technologies
          @portfolio.technologies.delete pt
          portfolioTech.each {|id|
            @technology = Technology.find_by_id(id)
            @portfolio.technologies << @technology
          }
        end
      redirect_to admin_root_path
      else
    end
  end

  def destroy
    if @portfolio.destroy
      redirect_to admin_portfolios_path
      else
        redirect_to admin_root_path
    end
  end

private

  def set_portfolio
    @portfolio = Portfolio.find(params[:id])
  end
  
  def portfolio_params
    params.require(:portfolio).permit(:id, :title, :description, :image_url, :githup_url, :dribbble_url, :demo_url, portfolio:[:technologies])
  end

  # def set_default_response_format
  #     request.format = :json
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	before_action :set_portfolio, only: [:show]
	before_filter :set_default_response_format, only: [:show, :portfolios_indexer]
  def index
  	@portfolios  = Portfolio.all
  end

  def show
  end
  
  def portfolios_indexer
    @portfolios_indexer  = Portfolio.page(params[:page] || 1).per(params[:per_page] || 1)
  end

private

	def set_portfolio
		@portfolio = Portfolio.find(params[:id])
	end

	def set_default_response_format
         request.format = :json
     end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/admin/portfolios/_form.html.erb
<%= form_for  [:admin, @portfolio] do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title  %>

  <%= f.label :description %>
  <%= f.text_field :description  %>
  
  <%= f.label :image_url %>
  <%= f.text_field :image_url  %>
  
  <%= f.label :githup_url %>
  <%= f.text_field :githup_url  %>

  <%= f.label :dribbble_url %>
  <%= f.text_field :dribbble_url  %>

  <%= f.label :demo_url %>
  <%= f.text_field :demo_url  %>
  <%= f.label :technologies %>
  <div class="input-field col s12">
    <%= f.collection_select(:technologies, Technology.all, :id, :name, {:prompt => true}, {:multiple => true}) %>
  </div>

  <%=f.submit "update portfolio"%>

<%end%>

app/views/admin/portfolios/edit.html.erb
<div class="container">
  <%= render "form"%>
</div>

app/views/admin/portfolios/index.html.erb
<%= render 'admin/sections/navbar' %>
<%= render 'admin/sections/admin_portfolio' %>

app/views/admin/portfolios/new.html.erb
<div class="container">
	<%= render "form"%>
</div>

app/views/admin/sections/_admin_portfolio.html.erb
<section id="portoflio">
  <div class="row">
   <div class="portoflio valign-wrapper">
    <div class="row container">
      <div class="portoflio-head">
        <h3 class="center-align portoflio-h3 ">PORTFOLIO</h3>
        <p class="divider"></p>
      </div>
        <%= react_component("AdminPortfolios")%>
      </div>
    </div>
  </div>
</section>

app/views/admin/sections/_navbar.html.erb
<div id="logo">
  <header>
    <div class="navbar-fixed">
       <nav>
          <div class="nav-wrapper container-wide nav-admin">
            <a href="#top" class="brand-logo">Admin</a>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
              <li><%= link_to "Add Portoflio",new_admin_portfolio_path %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
            <ul class="side-nav" id="mobile-demo">
              <li><%= link_to "Add Portoflio",new_admin_portfolio_path %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        </nav>
    </div>
  </header>
</div>

app/views/admin/sections/_portfolio.html.erb
<section id="portoflio">
  <div class="row">
   <div class="portoflio valign-wrapper">
    <div class="row container">
      <div class="portoflio-head">
        <h3 class="center-align portoflio-h3 ">PORTFOLIO</h3>
        <p class="divider"></p>
      </div>
        <%= react_component("Portfolios")%>
      </div>
    </div>
  </div>
</section>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'admin/admin', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="top">
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoufianeAkki</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="top">
    <%= yield %>
  </body>
</html>

app/views/portfolios/index.html.erb
<%= render 'sections/navbar' %>
<%= render 'sections/hero' %>
<%= render 'sections/portfolio' %>
<%= render 'sections/social' %>
<%= render 'sections/contact' %>

app/views/sections/_contact.html.erb
<section id="contact">
  <div class="row">
   <div class="contact valign-wrapper">
     <div class="contact-info center-align">
        <h3>GET IN TOUCH</h3>
        <p>if you have any question feel free to ask</p>
        <h4>
          <a href="mailto:vogdev@gmail.com" target="_top">vogdev@gmail.com</a>
        </h4>
     </div>
    </div>
  </div>
</section>

app/views/sections/_hero.html.erb
<div id="myLinks">
  <section>
    <div class="row">
     <div class="hero valign-wrapper">
      <div class="col s12 m12 center-align">
      <div class="info">
      <%= image_tag("SoufianeAKKi.jpg" , class: "circle responsive-img my-img") %>
         <h3>Frontend<span class="small">/</span>Backend Developer<span  class="small">&</span>Designer</h3>
         <h4>Hello, I'm <span>Soufiane Akki</span></h4>
         <p>Frontend / Backend Developer & Designer <br>
                focused on web trends and interactivity<br>
                Check out my <a href="#portoflio" class="portoflio-link">Portoflio</a>
         </p>
      </div>
      </div>
      </div>
    </div>
  </section>
</div>

app/views/sections/_navbar.html.erb
<div id="logo">
  <header>
    <div class="navbar-fixed">
       <nav>
          <div class="nav-wrapper container-wide">
            <a href="#top" class="brand-logo">AKKI.</a>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
              <li><a href="#portoflio">Portoflio</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
            <ul class="side-nav" id="mobile-demo">
              <li><a href="#portoflio">Portoflio</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div>
        </nav>
    </div>
  </header>
</div>

app/views/sections/_social.html.erb
<section id="social">
  <div class="row">
   <div class="social">
      <div class="col s12 m6 center-align ">
        <div class="dribbble valign-wrapper">
        <div class="social-info center-align">
         <%= image_tag("dribbble-logo.svg" , class: "dribbble-logo", alt: "dribbble-logo svg") %>
          <p>Want to see more?</p>
          <a href="https://dribbble.com/AkkiSoufiane" target="_blanck">
           <button class="btn purple darken-2" type="submit" name="action">/AkkiSoufiane
            <i class="material-icons right">launch</i>
          </button>
          </a>
        </div>
        </div>
      </div>
      <div class="col s12 m6 center-align">
        <div class="github valign-wrapper">
         <div class="social-info center-align">
         <%= image_tag("github-logo.svg" , class: "github-logo svg", alt: "github-logo svg") %>
            <p>Want to see code?</p>
            <a href="https://github.com/vogdev" target="_blanck">
             <button class="btn light-blue accent-4" type="submit" name="action"> @vogdev
              <i class="material-icons right">code</i>
            </button>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>